name: Upload to Discord

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and upload to Discord
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build GravityHelper.csproj --configuration Release --no-restore
    - name: Package and upload
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/gh-actions'
      env:
        ZIPNAME: GravityHelper
        GITHUB_SHA: ${{ github.sha }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        ZIPNAME=$ZIPNAME-${GITHUB_SHA:0:8}.zip
        zip -qq -r $ZIPNAME LICENSE everest.yaml bin/GravityHelper.dll Ahorn Audio Dialog Graphics Loenn Maps
        url=$(curl -H 'Content-Type: multipart/form-data' -X POST -F "file=@$ZIPNAME" "$DISCORD_WEBHOOK" | grep -Po 'cdn.discordapp.com\/.*?\.zip' | tr -d '\n')
        msg=$(git log -n 1 "--format=%B" | head -n 1 | tr -d '\n')
        curl -H 'Content-Type: application/json' -X POST -d "$(jq -n \
          --arg zipname "$ZIPNAME" \
          --arg url "$url" \
          --arg msg "$msg" \
          '{embeds: [{title: "Install \($zipname)", url: "https://0x0ade.ga/twoclick/?\($url)", description: $msg}]}' \
        )" "$DISCORD_WEBHOOK"
